package vista.interfaces;

import controller.Controller;

/**
 * @author Kristin
 */

public class InicioSesion extends javax.swing.JFrame {
    
    // Constructor de la ventana
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsuario = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        tfPass = new javax.swing.JPasswordField();
        ingresarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ImagenFondo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Opciones = new javax.swing.JMenu();
        Acerca_de = new javax.swing.JMenuItem();
        Limpiar_casillas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesion");
        setMinimumSize(new java.awt.Dimension(545, 335));
        setPreferredSize(new java.awt.Dimension(545, 335));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUsuario.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setText("Usuario:");
        getContentPane().add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        labelContraseña.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        labelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        labelContraseña.setText("Contraseña:");
        getContentPane().add(labelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        tfUsuario.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        getContentPane().add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 170, 150, -1));

        tfPass.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        getContentPane().add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 220, 150, -1));

        ingresarButton.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        ingresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/unlock-icon.png"))); // NOI18N
        ingresarButton.setText("Ingresar");
        ingresarButton.setContentAreaFilled(false);
        ingresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ingresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 263, -1, 30));

        jLabel3.setFont(new java.awt.Font("Batang", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inicio de Sesion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 310, 30));

        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Tarjeta abajo 1.png"))); // NOI18N
        getContentPane().add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 560, 310));

        Opciones.setText("Opciones");

        Acerca_de.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Acerca_de.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/info.png"))); // NOI18N
        Acerca_de.setText("Acerca de");
        Opciones.add(Acerca_de);

        Limpiar_casillas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        Limpiar_casillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/eraser.png"))); // NOI18N
        Limpiar_casillas.setText("Limpiar casillas");
        Limpiar_casillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_casillasActionPerformed(evt);
            }
        });
        Opciones.add(Limpiar_casillas);

        Menu.add(Opciones);

        setJMenuBar(Menu);

        setSize(new java.awt.Dimension(541, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarButtonActionPerformed
        String usuarioString = tfUsuario.getText();
        String passString = String.valueOf(tfPass.getPassword());
        
        try{
            Controller.inicializar(usuarioString, passString);
            //Usar messagebox operacion exitosa
            
            VentanaPrincipal VP = new VentanaPrincipal();
            VP.setVisible(true);
            
            this.setVisible(false); //Deberia cerrarse, no hacer no visible
            this.dispose();
        }catch(Exception e){
            Controller.mostrarMensaje(this, 
                    new Exception("No se pudo iniciar sesión. "
                            + "Revise los datos ingresados e intente de nuevo"));
        } 
    }//GEN-LAST:event_ingresarButtonActionPerformed

    private void Limpiar_casillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_casillasActionPerformed
        // TODO add your handling code here:
        this.tfPass.setText("");
        this.tfUsuario.setText("");
    }//GEN-LAST:event_Limpiar_casillasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acerca_de;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JMenuItem Limpiar_casillas;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Opciones;
    private javax.swing.JButton ingresarButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
