package vista.interfaces;

import java.util.ArrayList;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import controller.DataModel;
import controller.Controller;

/**
 * @author Kristin
 */

public class Tablas extends javax.swing.JFrame {

    public Tablas(ArrayList<ResultSet> resultados) {
        initComponents();
        
        try{
            ArrayList<String> tablas = Controller.obtenerNombreDeTablas();
        
            for(int i = 0; i < resultados.size(); i++){
                
                DataModel data = new DataModel(resultados.get(i));
                JScrollPane panel = new JScrollPane();
                JTable tabla = new JTable(data);
                panel.setViewportView(tabla);
                this.tabbedpaneTablas.addTab(tablas.get(i), panel);
            }
        }catch(Exception e){
            // Do something
        }
        
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedpaneTablas = new javax.swing.JTabbedPane();
        buttonET = new javax.swing.JButton();
        buttonCT = new javax.swing.JButton();
        ImagenFondo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Acerca_de = new javax.swing.JMenuItem();
        Regresar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 470));
        setPreferredSize(new java.awt.Dimension(600, 470));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tabbedpaneTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 628, 381));

        buttonET.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        buttonET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/recycle.png"))); // NOI18N
        buttonET.setText("Eliminar Tabla");
        buttonET.setContentAreaFilled(false);
        getContentPane().add(buttonET, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, 40));

        buttonCT.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        buttonCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/folder.png"))); // NOI18N
        buttonCT.setText("Crear Tabla");
        buttonCT.setContentAreaFilled(false);
        getContentPane().add(buttonCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 160, 40));

        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/ImagenTablas.png"))); // NOI18N
        getContentPane().add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 520));

        File.setText("Opciones");

        Acerca_de.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Acerca_de.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/info.png"))); // NOI18N
        Acerca_de.setText("Acerca de");
        Acerca_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acerca_deActionPerformed(evt);
            }
        });
        File.add(Acerca_de);

        Regresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.ALT_MASK));
        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/back.png"))); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        File.add(Regresar);

        Menu.add(File);

        setJMenuBar(Menu);

        setSize(new java.awt.Dimension(655, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Acerca_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acerca_deActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Acerca_deActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acerca_de;
    private javax.swing.JMenu File;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Regresar;
    private javax.swing.JButton buttonCT;
    private javax.swing.JButton buttonET;
    private javax.swing.JTabbedPane tabbedpaneTablas;
    // End of variables declaration//GEN-END:variables
}
