package vista.interfaces;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.event.TableModelListener;
import javax.swing.table.*;

/**
 * @author Kristin
 */
public class Resultado extends javax.swing.JFrame {
    
    ResultSet res;
    ResultSetMetaData resMetaData;
    //TableModel modeloDeDatos;
    
    private class DataModel extends AbstractTableModel{
        
        @Override
        public int getRowCount(){
            int cont = 0;
            try{  
                while(res.next())
                    cont++;
                res.beforeFirst(); //Devuelve el cursor
            }catch(Exception e){
                //
            }
            return cont-1;
        }
        
        @Override 
        public int getColumnCount(){
            int count = 0;
            try{
                count = resMetaData.getColumnCount();
            }catch(Exception e){
                //
            }
            return count;
        }
        
        @Override
        public Object getValueAt(int filaIndex, int columnaIndex){
            try{
                int cont = 0;
                while(res.next() && cont <= filaIndex)
                {
                    cont++;
                }
                String obj = res.getObject(columnaIndex+1).toString();
                return obj; 
            }catch(Exception e){
                //
            }
            return null;
        }
        
        /*
        @Override
        public Class<?> getColumnClass(int columna){
            try{
                String clase = resMetaData.getColumnClassName(columna);
                return Class.forName(clase);
            }
            catch(Exception e){
                //
            }
            return null;
        }*/
        
        @Override
        public String getColumnName(int columna){
            try{   
                return resMetaData.getColumnLabel(columna+1);
            }catch(Exception e){
                //
            }
            return null;
        }
    }
    
    public Resultado(ResultSet res) throws Exception{
        initComponents();
        this.res = res;
        
        try{
            this.resMetaData = res.getMetaData();
        }
        catch(Exception e){
            throw e;
        }
        
        DataModel modelo = new DataModel();
        modelo.fireTableDataChanged();
        tableResultante.setModel(modelo);
        tableResultante.validate();
        //((DataModel)tableResultante.getModel()).fireTableDataChanged();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaExpresion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableResultante = new javax.swing.JTable();
        labelExpresion = new javax.swing.JLabel();
        labelTR = new javax.swing.JLabel();
        ImagenFondo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Ayuda = new javax.swing.JMenuItem();
        Acerca_de = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resultado");
        setMinimumSize(new java.awt.Dimension(407, 374));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textAreaExpresion.setColumns(20);
        textAreaExpresion.setRows(5);
        jScrollPane1.setViewportView(textAreaExpresion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 63, 370, 110));

        tableResultante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableResultante);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 470, 140));

        labelExpresion.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        labelExpresion.setText("Expresión:");
        getContentPane().add(labelExpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        labelTR.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        labelTR.setText("Tabla Resultante:");
        getContentPane().add(labelTR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/bitmap1.png"))); // NOI18N
        getContentPane().add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        File.setText("File");

        Ayuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        Ayuda.setText("Ayuda");
        File.add(Ayuda);

        Acerca_de.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Acerca_de.setText("Acerca de");
        Acerca_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acerca_deActionPerformed(evt);
            }
        });
        File.add(Acerca_de);

        Menu.add(File);

        setJMenuBar(Menu);

        setSize(new java.awt.Dimension(522, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Acerca_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acerca_deActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Acerca_deActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acerca_de;
    private javax.swing.JMenuItem Ayuda;
    private javax.swing.JMenu File;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelExpresion;
    private javax.swing.JLabel labelTR;
    private javax.swing.JTable tableResultante;
    private javax.swing.JTextArea textAreaExpresion;
    // End of variables declaration//GEN-END:variables
}
