package vista.interfaces;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.*;
import java.util.ArrayList;

/**
 * @author Kristin
 */
public class Resultado extends javax.swing.JFrame {
    
    AbstractTableModel modelo;
    
    private class DataModel extends AbstractTableModel{
        ArrayList<String> headers;
        ArrayList<ArrayList<Object>> objetos;
        ArrayList<String> clasesPorColumna;
        
        public DataModel(ResultSet res){
            this.headers = new ArrayList<>();
            this.objetos = new ArrayList<>();
            this.clasesPorColumna = new ArrayList<>();
            
            ResultSetMetaData metaData = null;
            
            try{
                metaData = res.getMetaData();
                
                for(int i = 1; i <= metaData.getColumnCount(); i++){
                    headers.add(metaData.getColumnLabel(i));
                    clasesPorColumna.add(metaData.getColumnClassName(i));
                }
                
                while(res.next()){
                    ArrayList<Object> filaDeObjetos = new ArrayList<>();
                    
                    for(int i = 1; i <= headers.size(); i++)
                        filaDeObjetos.add(res.getObject(i));
                    
                    objetos.add(filaDeObjetos);
                }      
            }
            catch(Exception e){
                System.out.println("No se ha podido obtener los metadatos");
            }
            
        }
        
        @Override
        public int getRowCount(){
            return objetos.size();
        }
        
        @Override
        public int getColumnCount(){
           return headers.size();
        }
        
        @Override
        public Object getValueAt(int filaIndex, int columnaIndex){
            return objetos.get(filaIndex).get(columnaIndex);
        }
        
        @Override
        public Class<?> getColumnClass(int columna){
            try{
                return Class.forName(clasesPorColumna.get(columna));
            }catch(Exception e){
                System.out.println("No se pudo contruir la clase, porque no se ha encontrado");
            }
            return null;
        }
        
        @Override
        public String getColumnName(int columna){
            return headers.get(columna);
        }
    }
    
    public Resultado(ResultSet res) throws Exception{
        
        this.modelo = new DataModel(res); 
        
        initComponents();
        
        //modeloDeDatos.fireTableDataChanged();
        
        //tableResultante.updateUI();
        //tableResultante.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaExpresion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableResultante = new javax.swing.JTable();
        labelExpresion = new javax.swing.JLabel();
        labelTR = new javax.swing.JLabel();
        ImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resultado");
        setMinimumSize(new java.awt.Dimension(407, 374));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textAreaExpresion.setColumns(20);
        textAreaExpresion.setRows(5);
        jScrollPane1.setViewportView(textAreaExpresion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 63, 370, 110));

        tableResultante.setModel(this.modelo);
        jScrollPane2.setViewportView(tableResultante);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 470, 140));

        labelExpresion.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        labelExpresion.setText("Expresión:");
        getContentPane().add(labelExpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        labelTR.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        labelTR.setText("Tabla Resultante:");
        getContentPane().add(labelTR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/bitmap1.png"))); // NOI18N
        getContentPane().add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelExpresion;
    private javax.swing.JLabel labelTR;
    private javax.swing.JTable tableResultante;
    private javax.swing.JTextArea textAreaExpresion;
    // End of variables declaration//GEN-END:variables
}
