/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.interfaces;

/**
 *
 * @author Kristin
 */
public class Tablas extends javax.swing.JFrame {

    /**
     * Creates new form Tablas
     */
    public Tablas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedpaneTablas = new javax.swing.JTabbedPane();
        buttonET = new javax.swing.JButton();
        buttonCT = new javax.swing.JButton();
        ImagenFondo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Ayuda = new javax.swing.JMenuItem();
        Acerca_de = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 470));
        setPreferredSize(new java.awt.Dimension(600, 470));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tabbedpaneTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 628, 381));

        buttonET.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        buttonET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/recycle.png"))); // NOI18N
        buttonET.setText("Eliminar Tabla");
        buttonET.setContentAreaFilled(false);
        getContentPane().add(buttonET, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, 40));

        buttonCT.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        buttonCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/folder.png"))); // NOI18N
        buttonCT.setText("Crear Tabla");
        buttonCT.setContentAreaFilled(false);
        getContentPane().add(buttonCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 160, 40));

        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/ImagenTablas.png"))); // NOI18N
        getContentPane().add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 520));

        File.setText("File");

        Ayuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        Ayuda.setText("Ayuda");
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });
        File.add(Ayuda);

        Acerca_de.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Acerca_de.setText("Acerca de");
        Acerca_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acerca_deActionPerformed(evt);
            }
        });
        File.add(Acerca_de);

        Menu.add(File);

        setJMenuBar(Menu);

        setSize(new java.awt.Dimension(655, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AyudaActionPerformed

    private void Acerca_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acerca_deActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Acerca_deActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acerca_de;
    private javax.swing.JMenuItem Ayuda;
    private javax.swing.JMenu File;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton buttonCT;
    private javax.swing.JButton buttonET;
    private javax.swing.JTabbedPane tabbedpaneTablas;
    // End of variables declaration//GEN-END:variables
}
